src/arrow1.rs, src/arrow2.rs, src/lib.rs
Slowly looking more like (what I imagine to be) idiomatic Rust
- Refactors the bloated high-level functions into lower level functions that return `Result<Vec<u8>, parquet::errors::ParquetError>` or `Result<Vec<u8>, arrow2::error::ArrowError>`. 
- Use the `?` operator in each read/write function for better conciseness
- Feature gated top-level imports
Resolves most of #24
=> Refactor code into lower-level functions, use `?` operator

src/lib.rs
Seems better to have `readParquet` and `readParquet2` than `readParquet1` and `readParquet2`
=> Rename arrow-rs api as default

.github/workflows/test.yml, scripts/build-node-tests.sh, scripts/build.sh
Only build Node bundles during Node CI runs. Closes #35
=> Faster builds on Node CI tests

README.md
=> ZSTD mac instructions in readme

Cargo.toml
Saves 331KB on the uncompressed default wasm bundle.
Although this actually makes the brotli-compressed wasm bundle 1kb _larger_!! Though the gzip-compressed wasm bundle is still 60kb smaller.
Brotli encoded wasm sizes (with arrow1):
- `opt-level = s` with console_error_panic_hook: 855246
- `opt-level = s` without console_error_panic_hook: 824049
- `opt-level = z` with console_error_panic_hook: 856203
- `opt-level = z` without console_error_panic_hook: 855934
So let's go with `opt-level = s` and without `console_error_panic_hook` as the default
Closes https://github.com/kylebarron/parquet-wasm/issues/45
=> Keep opt-level = s and remove `console_error_panic_hook`

src/arrow1/reader.rs, src/arrow1/wasm.rs, src/arrow1/writer.rs, src/arrow2/reader.rs, src/arrow2/wasm.rs, src/arrow2/writer.rs, src/arrow2/writer_properties.rs, src/common/writer_properties.rs
=> Docstrings for public functions, structs, enums

.gitignore, package.json, tsconfig.docs.json, typedoc.json, yarn.lock
I'm blown away by the Rust and TS ecosystems.
- I write docstrings in Rust
- Full jsdoc comments are auto generated from the Rust docstrings in the generated `.d.ts` files during `wasm-pack`
- Call `typedoc`, to auto-generate docs from all the types and jsdocs in the `.d.ts` files
- Run `gh-pages` to publish to the `gh-pages` branch
Voila! 😻 It just works!!
https://kylebarron.dev/parquet-wasm/
=> Working typedoc

bench/bench.ts, bench/make_data.py, bench/poetry.lock, bench/pyproject.toml, package.json, yarn.lock
For #54 
tldr; with this basic (numerical) example data, arrow1 seems to be 30% faster than arrow2 for snappy-compressed parquet.
=> Create arrow1/arrow2 read benchmarks

scripts/build.sh
To solve bundling problems in https://github.com/visgl/loaders.gl/pull/2103. I found that the best way to solve the bundling issue for use in another _library_ was to use the node import for node and the esm import for bundling. However the esm bundle created by `wasm-pack` includes `import.meta.url`, which is a syntax error.
I'll leave this functionality undocumented for now because this API could change.
Somewhat related to https://github.com/kylebarron/parquet-wasm/issues/89.
References:
- https://github.com/iotaledger/identity.rs/pull/340
=> esm2 entrypoint with no import.meta.url

Cargo.lock, Cargo.toml, README.md, scripts/build.sh, src/lib.rs
Closes https://github.com/kylebarron/parquet-wasm/issues/115
=> Simplify cargo features

Cargo.lock, Cargo.toml
clap 3.2 added deprecations that don't pass clippy
=> pin clap to 3.1.*

README.md, scripts/build.sh
Closes https://github.com/kylebarron/parquet-wasm/issues/155. Preventing both APIs from being built at the same time (using `cfg(all(feature = "arrow1", and not arrow2`) seemed to be more difficult than it was worth
=> Make arrow2 the default bundle

src/arrow2/error.rs, src/arrow2/metadata.rs, src/arrow2/mod.rs, src/arrow2/reader_async.rs, src/arrow2/schema.rs, src/arrow2/wasm.rs, src/common/fetch.rs
Updates:
- Correctly handle a parquet fragment with a separate `url`. The `url` should be the **base** path
- Update `readRowGroupAsync` to take a _row group metadata_ instead of an index. This should make it easier to handle statistics and passing in a specific row group. It also means that manually passing in the arrow schema is also required.
Todo:
- Expose statistics from the struct to make it easier to filter on row groups.
=> Updated row group async reading

Cargo.lock, Cargo.toml, scripts/build.sh, src/arrow2/reader_async.rs, src/arrow2/wasm.rs, src/common/fetch.rs, www/async_testing.js
It turns out the issues around 
```
error: Only features sync,macros,io-util,rt,time are supported on wasm.
--> /Users/kyle/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.0/src/lib.rs:462:1
|
462 | compile_error!("Only features sync,macros,io-util,rt,time are supported on wasm.");
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
were coming from unused arrow1 apis
supersedes https://github.com/kylebarron/parquet-wasm/pull/201, closes https://github.com/kylebarron/parquet-wasm/issues/200
=> Use reqwest for async apis (attempt 2)

Cargo.lock, Cargo.toml
It looks like the `import env` issue from https://github.com/gyscos/zstd-rs/issues/205 is actually fixed by passing `wasm` and `thin` to zstd
From https://github.com/kylebarron/parquet-wasm/pull/271/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R115-R120
=> zstd features

README.md, package.json, src/arrow2/ffi.rs, src/arrow2/reader.rs, src/arrow2/wasm.rs, tests/js/arrow2-ffi.ts, tests/js/arrow2.ts, tests/js/index.ts, tests/js/utils.ts, yarn.lock
This enables parquet-wasm to work with the latest release of arrow-js-ffi. See https://github.com/kylebarron/arrow-js-ffi/pull/37
=> Use StructArray for FFI RecordBatches

.github/workflows/pr-manipulation.yml, .github/workflows/test.yml, scripts/report_build.sh
I would have liked to do a head vs target % change (apparently there's a way involving artifacts), but this is a sufficiently useful gauge. Presumably the artifacts required for that would also be used in package publishing.
As far as I can tell, it's only the JS bindings that differ between targets, so we can probably just do `pkg/esm/*.wasm` and be done with it.
=> CI production build size summary

Cargo.lock, Cargo.toml, README.md, src/writer_properties.rs
It seems like the arrow crate has gained support for `lz4_raw` [some time ago](https://github.com/apache/arrow-rs/commit/4e1247e8c03f36940a912256e2d94f49a1b581df) behind the `lz4` flag.
=> feat:  add lz4_raw support for `arrow1`

src/read_options.rs, src/reader_async.rs, src/wasm.rs
- Rename `AsyncParquetFile` to `ParquetFile`
- Combine object-store reader and local file reader into single `ParquetFile` API. 
- Remove `SharedIO` trait, since now we only have a single struct.
- Remove `with_batch_size` and `select_columns`. I don't see a need for the `ParquetFile` struct itself to maintain any reader state. That information is only used in the read phase, not the constructor phase, and so I think it's fine to pass those options into `read` or `stream`.
- Remove `readRowGroup` in favor of `read`. `read` now has options including a `rowGroups` parameter, that takes a list of integers.
- Define `ReaderOptions` struct for read options, used by both sync and async readers.
I couldn't get the row group selection to work in `stream()` here …
=> Update async API

README.md
Ref https://github.com/kylebarron/parquet-wasm/issues/489#issuecomment-2068478471
=> Update jsdelivr link

.github/workflows/docs-website.yml, .github/workflows/test.yml
upload-artifact and download-artifact v3 are EOL, which was causing CI to fail.
=> bump github actions versions

.github/workflows/docs-website.yml, .github/workflows/test.yml, Cargo.toml
We shouldn't need to check all combinations of the compressors features, because we don't do anything in our own user code about that. Those only get passed on to the upstream `parquet` crate, and it's their problem if a combination of decompressors is invalid. 
This speeds up the `check` CI run **from 10.5 minutes to 1 minute**
We really just want to check:
```
reader 
writer 
async 
debug 
```
=> Remove compressions from check-all-features
