kylebarron/parquet-wasm

Cargo.toml, src/lib.rs, www/index.js
Seems to be a bit faster (and safer Rust), but most notably, the generated IPC just works out of the box in Arrow JS.
Ignore the ugly newbie rust code 😂
=> Switch to Arrow2/Parquet2

src/lib.rs, www/index.js
Helpful examples:
- https://github.com/jorgecarleitao/arrow2/blob/81bfaddb92f432ae25bff4e9fdf200159ecebafe/examples/parquet_write.rs
- https://github.com/jorgecarleitao/arrow2/blob/81bfaddb92f432ae25bff4e9fdf200159ecebafe/examples/ipc_file_read.rs
- https://github.com/jorgecarleitao/arrow2/blob/4bbfb252594902a5e7e0286df307015c6f1aca8e/examples/parquet_write_record.rs
=> Working writer!

.gitignore, README.md, scripts/build.sh
Distribute three separate endpoints for use by a bundler, node, and ESM.
=> Better bundling

src/arrow1/wasm.rs, src/arrow2/wasm.rs, src/utils.rs
=> Helper to copy vec<u8> to Uint8Array

src/arrow1/writer_properties.rs, src/arrow2/mod.rs, src/arrow2/wasm.rs, src/arrow2/writer.rs, src/arrow2/writer_properties.rs, src/common/mod.rs, src/common/writer_properties.rs, src/lib.rs
=> WriterPropertiesBuilder for arrow2

Cargo.toml, scripts/build-node-tests.sh, scripts/build.sh, src/lib.rs
Closes #44.
Really getting a proliferation of features, but at this point seems worthwhile to have fine-grained control for bundle size.
=> Compression-specific features

README.md, src/arrow1/wasm.rs, src/arrow1/writer_properties.rs, src/arrow2/wasm.rs, src/arrow2/writer_properties.rs, src/utils.rs
Writing typedoc comments on every `#[wasm_bindgen]` export in the rust docstrings!!
=> Update docstrings and readme

README.md, scripts/build.sh, typedoc.json
=> Rename parquet_wasm bundle to "bundler"

.github/workflows/test.yml, Cargo.lock, Cargo.toml, src/arrow1/reader.rs, src/arrow1/writer.rs, src/arrow1/writer_properties.rs, src/arrow2/reader.rs, src/arrow2/writer.rs, src/arrow2/writer_properties.rs, src/utils.rs
=> Add clippy

src/arrow1/wasm.rs, src/arrow2/wasm.rs, tests/js/arrow1.ts, tests/js/arrow2.ts
Closes https://github.com/kylebarron/parquet-wasm/issues/91
=> Check that input exists/is a uint8array

.gitignore, Cargo.lock, Cargo.toml
Closes https://github.com/kylebarron/parquet-wasm/pull/101, Closes https://github.com/kylebarron/parquet-wasm/pull/99
=> Update to arrow and parquet 12.0

.github/workflows/docs-website.yml
Closes https://github.com/kylebarron/parquet-wasm/issues/84
=> Publish docs on tag

README.md
closes https://github.com/kylebarron/parquet-wasm/issues/97
=> Add published examples section to readme

.gitignore, Cargo.lock, Cargo.toml, README.md, src/arrow1/writer_properties.rs, src/arrow2/writer_properties.rs, src/common/writer_properties.rs, tests/js/arrow2.ts
Closes https://github.com/kylebarron/parquet-wasm/issues/104.
=> Add lz4_raw and zstd compressions for parquet2

.vscode/settings.json
=> Add vscode rust-analyzer target setting

Cargo.lock, Cargo.toml, src/arrow1/error.rs, src/arrow1/mod.rs, src/arrow1/reader.rs, src/arrow1/wasm.rs, src/arrow1/writer.rs, src/arrow2/error.rs, src/arrow2/mod.rs, src/arrow2/reader.rs, src/arrow2/reader_async.rs, src/arrow2/wasm.rs, src/arrow2/writer.rs, src/utils.rs, tests/js/arrow1.ts, tests/js/arrow2.ts
=> Cleaner error handling

Cargo.lock, Cargo.toml, src/arrow2/reader.rs, src/arrow2/writer.rs
=> Bump arrow2 version

Cargo.lock, Cargo.toml, src/arrow2/ffi.rs
=> ffi name changes

Cargo.lock, Cargo.toml, src/arrow2/reader.rs, src/arrow2/reader_async.rs, src/arrow2/schema.rs, src/arrow2/wasm.rs, tests/js/arrow2.ts
ref https://github.com/kylebarron/parquet-wasm/issues/208
=> bump arrow2 and parquet2

.github/workflows/test.yml, Cargo.toml, src/arrow2/error.rs, src/arrow2/mod.rs
Closes https://github.com/kylebarron/parquet-wasm/issues/217, Closes https://github.com/kylebarron/parquet-wasm/issues/199
Will need some code fixes 🙂
=> Cargo check with feature matrix combinations

Cargo.lock, Cargo.toml
closes https://github.com/kylebarron/parquet-wasm/issues/266
=> bump versions

Cargo.lock, Cargo.toml
closes https://github.com/kylebarron/parquet-wasm/pull/263
=> bump serde-wasm-bindgen

README.md
For https://github.com/kylebarron/parquet-wasm/issues/289. Doesn't close that out as I still need to update the docstring
=> Update README to note `drop` requirement

Cargo.lock, Cargo.toml, src/arrow2/reader.rs, src/arrow2/reader_async.rs, src/arrow2/wasm.rs, src/arrow2/writer.rs, src/arrow2/writer_properties.rs, src/bin/read_parquet2.rs, src/bin/write_parquet2.rs, tests/js/arrow2-ffi.ts, tests/js/arrow2-geo-metadata.ts, tests/js/arrow2.ts
Replaces https://github.com/kylebarron/parquet-wasm/pull/292 because I didn't want to deal with the merge conflicts
=> Depend on arrow-wasm (redux)

.gitignore, package.json, tests/js/arrow1-ffi.test.ts, tests/js/arrow1.test.ts, tests/js/arrow2-ffi.test.ts, tests/js/arrow2-geo-metadata.test.ts, tests/js/arrow2.test.ts, tests/js/index.test.ts, tests/js/index.ts, tests/js/utils.ts, yarn.lock
This uses the current setup in arrow-js-ffi for tests here
=> Switch to vitest

.github/workflows/test.yml, README.md, package.json, tests/js/index.test.ts
Closes https://github.com/kylebarron/parquet-wasm/pull/317
=> Use node 20 for tests

Cargo.lock, Cargo.toml, scripts/build.sh, templates/package.json
Closes https://github.com/kylebarron/parquet-wasm/issues/89; for https://github.com/visgl/loaders.gl/pull/2781#issuecomment-1804131173
Bumps to 0.6.0-beta.1
=> Add conditional exports

.github/dependabot.yml, Cargo.lock, Cargo.toml, README.md, bench/bench.ts, package.json, scripts/build.sh, src/read_options.rs, src/wasm.rs, tests/js/ffi.test.ts, tests/js/index.test.ts, tests/js/schema.test.ts, typedoc.json, www/async_testing.js, yarn.lock
- Update README to remove mentions of arrow1 and arrow2
- Update README to suggest use of ESM module by default
- Updated docstrings
- Added docstring type hints for ReaderOptions
- Added test for `readSchema`
=> Documentation updates for 0.6

CHANGELOG.md, templates/package.json
Closes https://github.com/kylebarron/parquet-wasm/issues/519
=> Export wasm paths from package.json

.cargo/config.toml, Cargo.lock, Cargo.toml
https://github.com/kylebarron/arrow-wasm/issues/8#issuecomment-2790469295
=> Handle getrandom update

README.md
Closes https://github.com/kylebarron/parquet-wasm/issues/708
=> docs: Add section to docs about hyparquet comparison
